name: Build fastgpt-pro-plugin images
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build-fastgpt-pro-plugin-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: labring/fastgpt-pro
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GH_PAT }}
      - name: Update submodules
        run: git submodule update --init --recursive # update git submodule
      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y nodejs npm
      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: labring
          password: ${{ secrets.GH_PAT }}
      - name: Login to Ali Hub
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_HUB_USERNAME }}
          password: ${{ secrets.ALI_HUB_PASSWORD }}
      - name: Set DOCKER_REPO_TAGGED based on branch or tag
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Git_Latest=ghcr.io/labring/fastgpt-pro-plugin:latest" >> $GITHUB_ENV
            echo "Git_Tag=ghcr.io/labring/fastgpt-pro-plugin:latest" >> $GITHUB_ENV
            echo "Ali_Latest=${{ secrets.ALI_IMAGE_NAME }}/fastgpt-pro-plugin:latest" >> $GITHUB_ENV
            echo "Ali_Tag=${{ secrets.ALI_IMAGE_NAME }}/fastgpt-pro-plugin:latest" >> $GITHUB_ENV
          else
            echo "Git_Tag=ghcr.io/labring/fastgpt-pro-plugin:${{ github.ref_name }}" >> $GITHUB_ENV
            echo "Git_Latest=ghcr.io/labring/fastgpt-pro-plugin:latest" >> $GITHUB_ENV
            echo "Ali_Tag=${{ secrets.ALI_IMAGE_NAME }}/fastgpt-pro-plugin:${{ github.ref_name }}" >> $GITHUB_ENV
            echo "Ali_Latest=${{ secrets.ALI_IMAGE_NAME }}/fastgpt-pro-plugin:latest" >> $GITHUB_ENV
          fi

      - name: Build and publish image for main branch or tag push event
        env:
          DOCKER_REPO_TAGGED: ${{ env.DOCKER_REPO_TAGGED }}
        run: |
          docker buildx build \
          -f projects/plugin/Dockerfile \
          --build-arg name=plugin \
          --platform linux/amd64,linux/arm64 \
          --label "org.opencontainers.image.source=https://github.com/labring/fastgpt-pro-plugin" \
          --label "org.opencontainers.image.description=fastgpt-pro-plugin image" \
          --push \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache \
          -t ${Git_Tag} \
          -t ${Git_Latest} \
          -t ${Ali_Tag} \
          -t ${Ali_Latest} \
          projects/plugin
